services:
  - type: web
    name: status-cast-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SHARED_SECRET
        generateValue: true
